# infrastructure/serverless.yml
service: synapsex-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  agentChat:
    handler: handler.agentChat
    events:
      - http:
          path: agent/chat
          method: post
  taskList:
    handler: handler.taskList
    events:
      - http:
          path: tasks
          method: get

plugins:
  - serverless-offline
